#+TITLE: TODO FOR PROJECT SPEECH RECOGNIZER
#+AUTHOR: Nabin Bhattarai, Miran Ghimire, Bikash Gupta, Kshitiz Shrestha, Pabin Luitel, Sabin Silwal
#+DATE: 2016-07-21

* Project Speech-Recognizer ToDo
** TODO Package Recorder
   SCHEDULED: <2016-07-21 Thu>   
   Package to Record Audio And save in wave file format
** TODO Package Audio
   SCHEDULED: <2016-07-23 Sat>
   Package which stores audio file which is easy for 
   further processing.
** TODO Package LanguageModel
   SCHEDULED: <2016-07-28 Thu>
   Package which gives the language model of english language
   languagemodel gives us the probable next word given previous 
   words, so we can only test the audio data to those probable
   next words.
   In this language model we doesn't use punctuations, we use words
   and we don't lemmatize words. words are used without modification.
** TODO Recognizer
   SCHEDULED: <2016-08-10 Wed>
   We are going to use HMM model to findout the possible next phonems according to their
   probability (having large probability is most probable phonems), 
   we train out main recognizer_core to findout the most probable phonems next in audio
   data, on that list of phonems for every phonems we find out next phonems and use HMM
   to find out most probable phonems, and according to those and previous phonems we findout
   the next phonems. Like this we get list of list of phonems and apply phonem model first
   to findout what the words might be, and with these words we use language model to find
   out what the sentences might be. The most probable sentence is the final output.
